import Vue from 'vue'
Vue.prototype.$countries = 'countries'
Vue.prototype.$cities = 'cities'
Vue.prototype.$zipcodes = 'zipcodes'
Vue.prototype.$plans = 'plans'
Vue.prototype.$tags = 'tags'
Vue.prototype.$groups = 'groups'
Vue.prototype.$coaches = 'coaches'
Vue.prototype.$announces = 'announces'
Vue.prototype.$blogs = 'blogs'
Vue.prototype.$uploadedImages = 'uploaded-images'

