import Vue from 'vue'
Vue.prototype.$imageUrl = 'http://localhost:9292/images/'
Vue.prototype.$countries = 'countries'
Vue.prototype.$cities = 'cities'
Vue.prototype.$zipcodes = 'zipcodes'
Vue.prototype.$plans = 'plans'
Vue.prototype.$tags = 'tags'
Vue.prototype.$images = 'images'
Vue.prototype.$groups = 'groups'
Vue.prototype.$coaches = 'coaches'
Vue.prototype.$announces = 'announces'
Vue.prototype.$blogs = 'blogs'
Vue.prototype.$subscriptions = 'subscriptions'
Vue.prototype.$clients = 'clients'
Vue.prototype.$links = 'links'
Vue.prototype.$uploadedImages = 'uploaded-images'

